### ISSUE TITLE
Add a workflow that validates that the script compiles at least

### ISSUE THREAD

**Issue by bdovaz** [Dinomite-Studios/unity-azure-pipelines-tasks-build-scripts#1]
Following this task you have created: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/283

I had the idea to create a workflow that creates a project in each LTS of Unity (2022, 6): https://unity.com/releases/editor/archive

I can help you with the PR because I have a project that does something similar.

P.S: you only added me as a contributor to one repository out of the 4 that are related to each other.

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-build-scripts
https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-docs
https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks-lib

**Comment by FejZa** [comment]
Hey, this is exactly why I created that task. For this repository I plan what you said,

there will be a pipeline that creates a new project in major Unity versions and then pulls in this package to make sure it builds/compiles correctly in all of them.

**Comment by FejZa** [comment]
I'll make sure to add you in the others as well, if you want

**Comment by bdovaz** [comment]
> I'll make sure to add you in the others as well, if you want

It would be nice!

> Hey, this is exactly why I created that task. For this repository I plan what you said,
> 
> there will be a pipeline that creates a new project in major Unity versions and then pulls in this package to make sure it builds/compiles correctly in all of them.

@FejZa if you need help, let me know. Here is a basic example of how I do it in other repositories with game.ci.

https://game.ci/docs/github/getting-started

```yaml
name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 1
```

```yaml
name: CI
on:
  push:
jobs:
  activation:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        unityVersion:
          - 2020.3.36f1
          - 2021.3.5f1
          - 2022.1.6f1
        targetPlatform:
          - WebGL

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Unity
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
```
